[package]

name = "pistoncore-sdl2_window"
version = "0.0.6"
authors = [
    "bvssvni <bvssvni@gmail.com>",
    "Coeuvre <coeuvre@gmail.com>",
    "gmorenz",
    "leonkunert <info@leonkunert.de>",
    "mitchmindtree <me@michellnordine.com>",
    "Christiandh",
    "Apointos",
    "ccgn",
    "reem",
    "TyOverby <ty@pre-alpha.com>"]
keywords = ["sdl2", "window", "piston"]
description = "A SDL2 back-end for the Piston game engine"
license = "MIT"
readme = "README.md"
repository = "https://github.com/pistondevelopers/sdl2_window.git"
homepage = "https://github.com/pistondevelopers/sdl2_window"

[dependencies.sdl2]
git = "https://github.com/AngryLawyer/rust-sdl2"
#version = "0.0.28"

[dependencies.pistoncore-window]
git = "https://github.com/pistondevelopers/window"
#version = "0.0.13"

[dependencies.pistoncore-input]
git = "https://github.com/pistondevelopers/input"
#version = "0.0.5"

[dependencies.shader_version]
git = "https://github.com/pistondevelopers/shader_version"
#version = "0.0.2"

[dependencies.gl]
git = "https://github.com/sinistersnare/gl-rs"
#version = "0.1.0"

[dependencies.quack]
git = "https://github.com/PistonDevelopers/quack"
#version = "0.0.13"

[dependencies.libc]


[lib]

name = "sdl2_window"
path = "src/lib.rs"

